[package]
name = "haby_core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version = "1", features = ["derive"]}
sqlx = {version = "0.8", features = ["macros"]}

[dev-dependencies]
proptest = "1"
